[package]
name = "cemoktra_github_io"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
leptos = { version = "0.7.7", features = ["csr"] }
leptos_router = "0.7.7"
thaw = { version = "0.4.4", features = ["csr"] }
typst = "0.13.0"
